export const SpecializationMap: Record<number, string> = {
  1: 'Cardiologist',
  2: 'Dermatologist',
  3: 'Endocrinologist',
  4: 'Gastroenterologist',
  5: 'Hematologist',
  6: 'Neurologist',
  7: 'Oncologist',
  8: 'Ophthalmologist',
  9: 'Orthopedist',
  10: 'Otolaryngologist',
  11: 'Pediatrician',
  12: 'Psychiatrist',
  13: 'Pulmonologist',
  14: 'Radiologist',
  15: 'Urologist',
};

export enum Specialization {
  Cardiologist = 1,
  Dermatologist = 2,
  Endocrinologist = 3,
  Gastroenterologist = 4,
  Hematologist = 5,
  Neurologist = 6,
  Oncologist = 7,
  Ophthalmologist = 8,
  Orthopedist = 9,
  Otolaryngologist = 10,
  Pediatrician = 11,
  Psychiatrist = 12,
  Pulmonologist = 13,
  Radiologist = 14,
  Urologist = 15,
}