export const SpecializationMap: Record<number, string> = {
  0: 'Cardiologist',
  1: 'Dermatologist',
  2: 'Endocrinologist',
  3: 'Gastroenterologist',
  4: 'Hematologist',
  5: 'Neurologist',
  6: 'Oncologist',
  7: 'Ophthalmologist',
  8: 'Orthopedist',
  9: 'Otolaryngologist',
  10: 'Pediatrician',
  11: 'Psychiatrist',
  12: 'Pulmonologist',
  13: 'Radiologist',
  14: 'Urologist',
};

export enum Specialization {
  Cardiologist = 0,
  Dermatologist = 1,
  Endocrinologist = 2,
  Gastroenterologist = 3,
  Hematologist = 4,
  Neurologist = 5,
  Oncologist = 6,
  Ophthalmologist = 7,
  Orthopedist = 8,
  Otolaryngologist = 9,
  Pediatrician = 10,
  Psychiatrist = 11,
  Pulmonologist = 12,
  Radiologist = 13,
  Urologist = 14,
}